package com.riceshop.manager;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout list; TextView summary; ArrayList<P> ps=new ArrayList<>(); android.content.SharedPreferences sp;
 static class P{String n;double b,s,q;P(String n,double b,double s,double q){this.n=n;this.b=b;this.s=s;this.q=q;}}
 String m(double x){return "₹"+String.format(Locale.US,"%.2f",x);}
 TextView t(String x,int z){TextView v=new TextView(this);v.setText(x);v.setTextSize(z);v.setPadding(12,12,12,12);return v;}
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("rice",0);load();ui();}
 void load(){String d=sp.getString("p","");if(d.isEmpty()){ps.add(new P("Nasreen",102,107,0));ps.add(new P("Suber",79,85,0));ps.add(new P("Tajmahal",40,45,0));ps.add(new P("Nasreen 2",95,102,0));}else for(String r:d.split("\\|")){String[]x=r.split("~");if(x.length==4)ps.add(new P(x[0],Double.parseDouble(x[1]),Double.parseDouble(x[2]),Double.parseDouble(x[3])));}}
 void save(){StringBuilder d=new StringBuilder();for(P p:ps){if(d.length()>0)d.append("|");d.append(p.n).append("~").append(p.b).append("~").append(p.s).append("~").append(p.q);}sp.edit().putString("p",d.toString()).apply();}
 void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(12,12,12,12);TextView h=t("🌾 Rice Shop Manager",25);h.setTextColor(Color.WHITE);h.setBackgroundColor(Color.rgb(23,107,58));r.addView(h);
 summary=t("",17);r.addView(summary);Button add=new Button(this);add.setText("+ Add Rice Product");add.setOnClickListener(v->dlg(-1));r.addView(add);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);r.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);render();}
 void render(){list.removeAllViews();double c=0,s=0,pf=0;for(int i=0;i<ps.size();i++){P p=ps.get(i);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(8,8,8,8);card.addView(t(p.n+"  | Cost "+m(p.b)+" | Sell "+m(p.s)+" | Profit/kg "+m(p.s-p.b),18));EditText q=new EditText(this);q.setHint("Quantity sold (kg)");q.setInputType(2|8192);if(p.q>0)q.setText(String.valueOf((int)p.q));card.addView(q);Button e=new Button(this);e.setText("Edit / Delete");e.setOnClickListener(v->dlg(i));card.addView(e);q.setOnFocusChangeListener((v,f)->{if(!f){try{p.q=Double.parseDouble(q.getText().toString());}catch(Exception x){p.q=0;}save();render();}});list.addView(card);c+=p.b*p.q;s+=p.s*p.q;pf+=(p.s-p.b)*p.q;}summary.setText("Cost: "+m(c)+"    Sales: "+m(s)+"    Profit: "+m(pf));}
 void dlg(int i){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this),cp=new EditText(this),spx=new EditText(this);n.setHint("Rice name");cp.setHint("Cost/kg");spx.setHint("Sell/kg");cp.setInputType(2|8192);spx.setInputType(2|8192);b.addView(n);b.addView(cp);b.addView(spx);if(i>=0){P p=ps.get(i);n.setText(p.n);cp.setText(""+p.b);spx.setText(""+p.s);}new AlertDialog.Builder(this).setTitle(i<0?"Add Product":"Edit Product").setView(b).setPositiveButton(i<0?"Add":"Save",(d,w)->{try{String x=n.getText().toString();double a=Double.parseDouble(cp.getText().toString()),z=Double.parseDouble(spx.getText().toString());if(i<0)ps.add(new P(x,a,z,0));else{P p=ps.get(i);p.n=x;p.b=a;p.s=z;}save();render();}catch(Exception e){Toast.makeText(this,"Enter valid values",0).show();}}).setNegativeButton("Cancel",null).show();}
}
